#!/usr/bin/env bash

root_dir=$(pwd)

# Erlang
if [[ $1 == "erlang" ]]; then
  for exercise in $(ls -1A erlang); do
    cd "$root_dir/erlang/$exercise" && rebar3 eunit

    [[ $? != 0 ]] && exit 1
  done
fi

cd $root_dir